name: Test triggers
run-name: Probando 3 triggers
on:
    push:
        branches: 
            - aprendiendo-github-actions
    pull_request: 
        types: [opened, closed]
    workflow_dispatch: 
        inputs:
            alerta:
                description: 'Nivel'
                required: true
                type: choice
                default: medio
                options:
                    - bajo
                    - medio
                    - alto
            tags:
                description: 'Comentario extra'
                required: false
                type: string
jobs:
    execute-hola-mundo:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3

            - name: ejecutar script
              run: node hola-mundo.js
        